### ISSUE TITLE
Include build file

### ISSUE THREAD

**Issue by theaqua** [xudafeng/autoresponsive-react#9]
Hi, thanks for your library!

I have small problem with browserify, because you're using pure ES6. I also have babel-transform, of course, but can you include full build file to `dist`, for example?

    [09:03:27] Starting 'scripts'...
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Parsing file /Users/e/dev/yard/frontend/node_modules/autoresponsive-react/lib/index.js: Unexpected token (126:6)
        at Deps.parseDeps (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/module-deps/index.js:436:28)
        at fromSource (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/module-deps/index.js:375:44)
        at /Users/e/dev/yard/frontend/node_modules/browserify/node_modules/module-deps/index.js:369:17
        at ConcatStream.<anonymous> (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
        at ConcatStream.emit (events.js:129:20)
        at finishMaybe (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
        at endWritable (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
        at ConcatStream.Writable.end (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
        at DuplexWrapper.onend (/Users/e/dev/yard/frontend/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
        at DuplexWrapper.g (events.js:199:16)
        at DuplexWrapper.emit (events.js:129:20)
        at /Users/e/dev/yard/frontend/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:934:16
        at process._tickCallback (node.js:355:11)

**Comment by xudafeng** [comment]
@theaqua dist file are all in `/assets`, exec `make server` to run this.

**Comment by theaqua** [comment]
@xudafeng can you add it to node package?

**Comment by xudafeng** [comment]
@theaqua sure,`npm i autoresponsive-react@1.1.5 `
